const topToursActionTypes = {
  FETCH_TOPTOURS_START: "FETCH_TOPTOURS_START",
  FETCH_TOPTOURS_SUCCESS: "FETCH_TOPTOURS_SUCCESS",
  FETCH_TOPTOURS_FAILURE: "FETCH_TOPTOURS_FAILURE",
};

export default topToursActionTypes;
