const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOGOUT_CURRENT_USER_START: "LOGOUT_CURRENT_USER_START",
  LOGOUT_CURRENT_USER_SUCCESS: "LOGOUT_CURRENT_USER_SUCCESS",
  LOGOUT_CURRENT_USER_FAILURE: "LOGOUT_CURRENT_USER_FAILURE",
};

export default UserActionTypes;
