const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOGOUT_CURRENT_USER_START: "LOGOUT_CURRENT_USER_START",
  LOGOUT_CURRENT_USER_SUCCESS: "LOGOUT_CURRENT_USER_SUCCESS",
  LOGOUT_CURRENT_USER_FAILURE: "LOGOUT_CURRENT_USER_FAILURE",
  GET_USER_BOOKINGS_START: "GET_USER_BOOKINGS_START",
  GET_USER_BOOKINGS_SUCCESS: "GET_USER_BOOKINGS_SUCCESS",
  GET_USER_BOOKINGS_FAILURE: "GET_USER_BOOKINGS_FAILURE",
};

export default UserActionTypes;
